### ISSUE TITLE
Remove git commits/branches check

### ISSUE THREAD

**Issue by sviperm** [labmlai/labml#65]
Hello there!

First of all thanks for your library, used it in my recent open source project!

Now, I want to share my criticism.

I have another project, but there we decided to set remotes' names of our repo different from default: `bars` and `upstream`, there is no `origin` as you can see.

So I had this error:

.labml.yml:
```yaml
check_repo_dirty: false
experiments_path: '.labml'
web_api: 'secret'
```
Error:
```shell
Traceback (most recent call last):
  File "/media/sviperm/9740514d-d8c8-4f3e-afee-16ce6923340c3/sviperm/Documents/Aurora/Aurora.ContextualMistakes/src/train.py", line 395, in <module>
    train()
  File "/media/sviperm/9740514d-d8c8-4f3e-afee-16ce6923340c3/sviperm/Documents/Aurora/Aurora.ContextualMistakes/src/train.py", line 354, in train
    with experiment.record(name=MODEL_SAVE_NAME, exp_conf=args.__dict__) if args.labml else ExitStack():
  File "/media/sviperm/9740514d-d8c8-4f3e-afee-16ce6923340c3/sviperm/Documents/Aurora/Aurora.ContextualMistakes/venv/lib/python3.9/site-packages/labml/experiment.py", line 388, in rec
ord
    create(name=name,
  File "/media/sviperm/9740514d-d8c8-4f3e-afee-16ce6923340c3/sviperm/Documents/Aurora/Aurora.ContextualMistakes/venv/lib/python3.9/site-packages/labml/experiment.py", line 86, in crea
te
    _create_experiment(uuid=uuid,
  File "/media/sviperm/9740514d-d8c8-4f3e-afee-16ce6923340c3/sviperm/Documents/Aurora/Aurora.ContextualMistakes/venv/lib/python3.9/site-packages/labml/internal/experiment/__init__.py"
, line 511, in create_experiment
    _internal = Experiment(uuid=uuid,
  File "/media/sviperm/9740514d-d8c8-4f3e-afee-16ce6923340c3/sviperm/Documents/Aurora/Aurora.ContextualMistakes/venv/lib/python3.9/site-packages/labml/internal/experiment/__init__.py"
, line 225, in __init__
    self.run.repo_remotes = list(repo.remote().urls)
  File "/media/sviperm/9740514d-d8c8-4f3e-afee-16ce6923340c3/sviperm/Documents/Aurora/Aurora.ContextualMistakes/venv/lib/python3.9/site-packages/git/remote.py", line 553, in urls
    raise ex
  File "/media/sviperm/9740514d-d8c8-4f3e-afee-16ce6923340c3/sviperm/Documents/Aurora/Aurora.ContextualMistakes/venv/lib/python3.9/site-packages/git/remote.py", line 529, in urls
    remote_details = self.repo.git.remote("get-url", "--all", self.name)
  File "/media/sviperm/9740514d-d8c8-4f3e-afee-16ce6923340c3/sviperm/Documents/Aurora/Aurora.ContextualMistakes/venv/lib/python3.9/site-packages/git/cmd.py", line 545, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/media/sviperm/9740514d-d8c8-4f3e-afee-16ce6923340c3/sviperm/Documents/Aurora/Aurora.ContextualMistakes/venv/lib/python3.9/site-packages/git/cmd.py", line 1011, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/media/sviperm/9740514d-d8c8-4f3e-afee-16ce6923340c3/sviperm/Documents/Aurora/Aurora.ContextualMistakes/venv/lib/python3.9/site-packages/git/cmd.py", line 828, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git remote get-url --all origin
  stderr: 'fatal: No such remote 'origin''
```

So my question №1 is: why `labml` check git branches/remote/commits? What is the idea behind this logic? I think that library for training monitoring for ML project doesn't need to do that. If developer / data scientist want to track git and prevent training because of uncommited changes, he/she can write this logic by his own.

Question №2: if i set `check_repo_dirty: false` why labml still checking repo? And what is the default value of the parameter?

2 possible suggestions:
1. Put condition before `try` in [labml/internal/experiment/\_\_init\_\_.py](https://github.com/labmlai/labml/blob/8fd5df0919b05e832db0f035ac2c440e8b6ea3cc/labml/internal/experiment/__init__.py#L222) to prevent all this _git code_ :
    ```python
    if self.check_repo_dirty:
        try:
            repo = git.Repo(lab_singleton().path)
        
            self.run.repo_remotes = list(repo.remote().urls)
            self.run.commit = repo.head.commit.hexsha
            self.run.commit_message = repo.head.commit.message.strip()
            self.run.is_dirty = repo.is_dirty()
            self.run.diff = repo.git.diff()
        except git.InvalidGitRepositoryError:
            if not is_colab() and not is_kaggle():
                labml_notice(["Not a valid git repository: ",
                              (str(lab_singleton().path), Text.value)])
            self.run.commit = 'unknown'
            self.run.commit_message = ''
            self.run.is_dirty = True
            self.run.diff = ''
    ```
2. Or completely remove all this git tracking code or make it deprecated.

Thanks!

**Comment by vpj** [comment]
Git tracking (recording the commit and diff) is to be able to reproduce experiments. We've had a bunch instances before we wrote this library where we had  results that we couldn't reproduce because the code has changed. We had to try going back to old commits to find when it worked.

 `check_repo_dirty` checks if there are uncommitted changes before running an experiment. This is different from tracking the git commit. It just throws an error if there are uncommitted changes. This is probably not necessary for most projects.

I hope I answered your questions.

Will push a fix to avoid the above error.

**Comment by vpj** [comment]
https://github.com/labmlai/labml/commit/354e6f6a31da840cf793add4f63bc42d77fa5374

This should fix it. Can you please check.

Thanks

**Comment by sviperm** [comment]
Thanks for super-duper fast commit, I will check it in a few hours, right now model is training. How can I get an update? `pip install -U labml` or should install it from the source?

**Comment by vpj** [comment]
Pip install upgrade should work. I updated the pip package also

**Comment by sviperm** [comment]
Error is gone, but have this in my stout:
```
debug-model^3: 70ddb1bcd71a11ebb81e04d4c4213fd1
        [dirty]: "Add data"
Monitor experiment at https://app.labml.ai/run/70ddb1bcd71a11ebb81e04d4c4213fd1
```
Is it correct that labml output that I have uncomitted changes or not? If it's expected result, so you can close issue. Thank You!

**Comment by vpj** [comment]
Yeah, that's expected. Sorry for the late reply.
